### ISSUE TITLE
OpenAI - Func Tools Arguments Array Item Type Missing

### ISSUE THREAD

**Issue by vetha2k24** [superagentxai/superagentx#19]
Hi,

I am using superagentxai version 0.1.11 and wanted to test the openAI model with multi-agent.

Here is code:
`llm_config = {

        'llm_type': 'openai'
    }
    llm_client = LLMClient(llm_config=llm_config)

    prompt_template = PromptTemplate()

    memory = Memory(
        memory_config={"llm_client": llm_client}
    )
    serper_handler = SerperDevToolHandler()
    serper_engine = Engine(
        handler=serper_handler,
        llm=llm_client,
        prompt_template=prompt_template
    )

    scrape_handler = ScrapeHandler()

    engine_prompt = PromptTemplate(
        # system_message=system_prompt
    )
    content_engine = Engine(
        handler=scrape_handler,
        llm=llm_client,
        prompt_template=prompt_template
    )

    serper_agent = Agent(
        name="Serper Agent",
        role='',
        goal='',
        llm=llm_client,
        prompt_template=prompt_template,
        engines=[serper_engine],
        output_format=output_prompt,
        max_retry=1
    )

    content_agent = Agent(
        name="crawler Agent",
        goal="",
        role="",
        llm=llm_client,
        prompt_template=prompt_template,
        engines=[content_engine],
        max_retry=1
    )

    pipe = AgentXPipe(
        agents=[
            serper_agent,
            content_agent
        ],
        memory=memory,
    )
await pipe.flow(query_instructions="")`

When running it I received the following error:

`openai.BadRequestError: Error code: 400 - {'error': {'message': "Invalid schema for function 'scrap_content': In context=('properties', 'domain_urls'), array schema missing items.", 'type': 'invalid_request_error', 'param': 'tools[0].function.parameters', 'code': 'invalid_function_parameters'}}
`

Possible Solution:
1. In tool calls, you should create the 'items' schema in the properties of domain_urls. Because of domain_urls is list[str]

`'properties': {
                'domain_urls': {
                    'type': 'array',
                    'description': 'The domain urls.',
                     'items': {
                         "type": "string"
                    }
                }
}`

**Comment by SyedHabibM** [comment]
Will be deployed in the next rolling release.
